name: New Contributor Message

on:
  pull_request_target:

jobs:
  build:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      # Pinned to v2.0
      - uses: deborah-digges/new-pull-request-comment-action@224c179a9e23f65ec50ff3240b8716369dc415d7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Hey, thank you for opening your Pull Request !
            Newline test

            Make sure test `abc`

